# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('token', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('twitter_handle', models.CharField(blank=True, max_length=40)),
                ('homebase', models.CharField(blank=True, max_length=40)),
                ('profession', models.CharField(blank=True, max_length=40)),
                ('current_location', models.CharField(blank=True, max_length=40)),
                ('blurb', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
