# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160313_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='twitter_handle',
            new_name='ry_gen_name',
        ),
        migrations.AddField(
            model_name='person',
            name='ry_gen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_podcast',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='social_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='questions',
            field=models.ManyToManyField(to='person.Question'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(to='person.Tag'),
        ),
    ]
