# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_tag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homebase',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
